CityBusManagementSystem.Api/CityBusManagementSystem.UI/Controllers/RoutesDetailsController.cs
using CityBusManagement.Entity.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.UI.Controllers
{
    public class RoutesDetailsController : Controller
    {
        private IConfiguration _configuration;
        public RoutesDetailsController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public async Task<IActionResult> RouteDetails()
        {
            IEnumerable<RouteDetails> routeDetails = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "RoutesDetails/GetRouteDetails";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        routeDetails = JsonConvert.DeserializeObject<IEnumerable<RouteDetails>>(result);
                    }
                }
            }
            return View(routeDetails);
        }
        public IActionResult RouteDetailsEntry()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> RouteDetailsEntry(RouteDetails routeDetails)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(routeDetails), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "RoutesDetails/AddRouteDetails";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "RouteDetails  saved successfully!";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong entries!";
                    }
                }
            }
            return View();
        }
        public async Task<IActionResult> GetRouteDetails()
        {
            IEnumerable<RouteDetails> routeResult = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "RoutesDetails/GetRouteDetails";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        routeResult = JsonConvert.DeserializeObject<IEnumerable<RouteDetails>>(result);
                    }
                }
            }
            return View(routeResult);
        }
        public async Task<IActionResult> UpdateRouteDetails(int routeNo)
        {
            RouteDetails routeResult = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "RoutesDetails/UpdateRouteDetails?routeNo=" + routeNo;
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        routeResult = JsonConvert.DeserializeObject<RouteDetails>(result);
                    }
                }
            }
            return View(routeResult);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateRouteDetails(RouteDetails routedetails)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(routedetails), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "RoutesDetails/UpdateRouteDetails";
                using (var response = await client.PutAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "RouteDetails details Updated successfully!";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong entries!";
                    }
                }
            }
            return View();

        }



        public async Task<IActionResult> DeleteRouteDetails(int routeNo)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {

                string endPoint = _configuration["WebApiBaseUrl"] + "RoutesDetails/DeleteRouteDetails?routeNo=" + routeNo;
                using (var response = await client.DeleteAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Route details Deleted successfully!";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong entries!";
                    }
                }
            }
            return View();

        }

    }
}
   

CityBusManagementSystem.Api/CityBusManagementSystem.UI/Views/RoutesDetails/DeleteRouteDetails.cshtml
@model CityBusManagement.Entity.Models.RouteDetails


<form enctype="multipart/form-data">
    <h2>Delete RouteDetails</h2>

    

    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }

</form>
<div>
    <a asp-controller="RoutesDetails" asp-action="RouteDetails">View  List</a>
</div>

CityBusManagementSystem.Api/CityBusManagementSystem.UI/Views/RoutesDetails/RouteDetailsEntry.cshtml
@model CityBusManagement.Entity.Models.RouteDetails

<form method="post" enctype="multipart/form-data">

    <div class="h2">
        ROUTE DETAILS ENTRY
    </div>
    <div class="form-group">
        
           
        <label>Source</label>
        <input type="text" asp-for="source" class="form-control" placeholder="enter source " required />
    </div>
    <div class="form-group">
        <label>Destination</label>
        <input type="text" asp-for="destination" class="form-control" placeholder="enter destination" required />
    </div>
    <input type="submit" value="Save" class="btn btn-outline-success" />
    <input type="button" value="Reset" class="btn btn-outline-secondary" />
    <hr />
    @if (ViewBag.status == "Ok")
    {
    <div class="alert alert-success">
        @ViewBag.message
    </div> }
    else if (ViewBag.status == "Error")
    {
    <div class="alert alert-danger">
        @ViewBag.message
    </div>}
</form>

<div>
    <a asp-controller="RouteDetails" asp-action="RouteDetails">Back to List</a>
</div>

CityBusManagementSystem.Api/CityBusManagementSystem.UI/Views/RoutesDetails/Routedetails.cshtml
@model IEnumerable<CityBusManagement.Entity.Models.RouteDetails>


<div class="row">
    <div class="col-12">
        <h3>RouteDetails</h3>
        <hr />
        <table class="table table-light table-bordered table-hover">
            <thead>
                <tr>
                    <th>routeNo</th>
                    <th>source</th>
                    <th>destination</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var routeDetails in Model)
                {
                    <tr>
                        <td>@routeDetails.routeNo</td>
                        <td>@routeDetails.source</td>
                        <td>@routeDetails.destination</td>
                        <td><a asp-controller="RoutesDetails" asp-action="UpdateRouteDetails" asp-route-routeNo="@routeDetails.routeNo">Edit</a></td>
                        <td><a asp-controller="RoutesDetails" asp-action="DeleteRouteDetails" asp-route-routeNo="@routeDetails.routeNo">Delete</a></td>
                    </tr>
}
            </tbody>
        </table>
    </div>
</div>

CityBusManagementSystem.Api/CityBusManagementSystem.UI/Views/RoutesDetails/UpdateRouteDetails.cshtml
@model CityBusManagement.Entity.Models.RouteDetails


<form method="post" enctype="multipart/form-data">
    <h2>Update RouteDetails</h2><hr />
    <div class="form-group">
        <div class="form-group">
        <label>Routeno</label>
        <input type="text" asp-for="routeNo" class="form-control" placeholder="Enter routeno" required />
    </div>

        <label>Source</label>
        <input type="text" asp-for="source" class="form-control" placeholder="Enter Source" required />
    </div>
    <div class="form-group">
        <label>Destination</label>
        <input type="text" asp-for="destination" class="form-control" placeholder="Enter destination" required />
    </div>
    

    <input type="submit" value="Update" class="btn btn-success" />

    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }
</form>
<div>
    <a asp-controller="RouteDetails" asp-action="RouteDetails">View  List</a>
</div>