CityBusManagementSystem.Api/CityBusManagementSystem.UI/Controllers/BusStopController.cs
using CityBusManagement.Entity.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace CityBusManagementSystem.UI.Controllers
{
    public class BusStopController : Controller
    {
        private IConfiguration _configuration;
        public BusStopController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public async Task<IActionResult> BusStop()
        {
            IEnumerable<BusStop> busStop = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "BusStop/GetBusStop";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        busStop = JsonConvert.DeserializeObject<IEnumerable<BusStop>>(result);
                    }
                }
            }
            return View(busStop);
        }

        public IActionResult BusStopEntry()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> BusStopEntry(BusStop busStop)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(busStop), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "BusStop/AddBusStop";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "BusStop details saved successfully!";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong entries!";
                    }
                }
            }
            return View();
        }
    }
}

CityBusManagementSystem.Api/CityBusManagementSystem.UI/Controllers/EmployeeController.cs
using CityBusManagement.Entity.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace CityBusManagementSystem.UI.Controllers
{
    public class EmployeeController : Controller
    {
        private IConfiguration _configuration;
        public EmployeeController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public async Task<IActionResult> Employee()
        {
            IEnumerable<Employee> employee = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "Employee/GetEmployeeDetails";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        employee = JsonConvert.DeserializeObject<IEnumerable<Employee>>(result);
                    }
                }
            }
            return View(employee);
        }
        public IActionResult EmployeeEntry()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> EmployeeEntry(Employee employee)
        {
            
                ViewBag.status = "";
                using (HttpClient client = new HttpClient())
                {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(employee), Encoding.UTF8, "application/json");
                    string endPoint = _configuration["WebApiBaseUrl"] + "Employee/AddEmployeeDetails";
                    using (var response = await client.PostAsync(endPoint, content))
                    {
                        if (response.StatusCode == System.Net.HttpStatusCode.OK)
                        {
                            ViewBag.status = "Ok";
                            ViewBag.message = "Employee details saved successfully!";
                        }
                        else
                        {
                            ViewBag.status = "Error";
                            ViewBag.message = "Wrong entries!";
                        }
                    }
                }
                return View();
            }
        }
    }

CityBusManagementSystem.Api/CityBusManagementSystem.UI/Controllers/LoginController.cs
using CityBusManagement.Entity.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace CityBusManagementSystem.UI.Controllers
{
    public class LoginController : Controller
    {
        private IConfiguration _configuration;
        public LoginController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(AdminInfo adminInfo)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(adminInfo), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "Token/Login";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                        return RedirectToAction("RouteDetailsEntry", "RouteDetails");
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong credentials!";
                    }
                }
            }
            return View();
        }
    }
}

CityBusManagementSystem.Api/CityBusManagementSystem.UI/Controllers/TripController.cs
using CityBusManagement.Entity.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace CBMS.UI.Controllers
{
    public class TripController : Controller
    {
        private IConfiguration _configuration;
        public TripController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public async Task<IActionResult> Trip()
        {
            IEnumerable<Trip> tripDetails = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "Trip/GetTripDetails";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        tripDetails = JsonConvert.DeserializeObject<IEnumerable<Trip>>(result);
                    }
                }
            }
            return View(tripDetails);
        
    }
        public IActionResult TripEntry()
        {
            return View();
        }
        
       
            [HttpPost]
            public async Task<IActionResult> TripEntry(Trip tripDetails)
            {
                ViewBag.status = "";
                using (HttpClient client = new HttpClient())
                {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(tripDetails), Encoding.UTF8, "application/json");
                    string endPoint = _configuration["WebApiBaseUrl"] + "Trip/AddTripDetails";
                    using (var response = await client.PostAsync(endPoint, content))
                    {
                        if (response.StatusCode == System.Net.HttpStatusCode.OK)
                        {
                            ViewBag.status = "Ok";
                            ViewBag.message = "Trip details saved successfully!";
                        }
                        else
                        {
                            ViewBag.status = "Error";
                            ViewBag.message = "Wrong entries!";
                        }
                    }
                }
                return View();
            }
    }
}

CityBusManagementSystem.Api/CityBusManagementSystem.UI/Views/Shared/New_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CityBusManagementS.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>

        <div class="text-center">
            <div class="header">
                <h1 class="display-4">CITY BUS MANAGEMENT SYSTEM</h1>
            </div>
        </div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CityBusManagement.UI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RoutesDetails" asp-action="RouteDetailsEntry">Route Details </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BusDetails" asp-action="BusDetailsEntry">Bus Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BusStop" asp-action="BusStopEntry">Bus stop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trip" asp-action="TripEntry">Trip </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="EmployeeEntry">Employee </a>
                        </li>
                        }
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="footer">
            <div class="container">
                &copy; 2022 - CityBusManagement.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

CityBusManagementSystem.Api/CityBusManagementSystem.UI/Views/Shared/_Layout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{ }
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CityBusManagementSystem.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="text-center">
            <div class="header">
                <h1 class="display-4">CITY BUS MANAGEMENT SYSTEM</h1>
            </div>
        </div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CityBusManagementSystem.UI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="RoutesDetails" asp-action="RouteDetailsEntry">RouteDetails</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="BusDetails" asp-action="BusDetailsEntry">BusDetails</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="BusStop" asp-action="AddBusStop">BusStop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Trip" asp-action="TripEntry">Trip</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Epmloyee" asp-action="EmployeeEntry">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Login" asp-action="Login">Login</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CityBusManagementSystem.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

CityBusManagementSystem.Api/CityBusManagementSystem.UI/Views/Shared/_PublicLayout.cshtml
@model CityBusManagement.Entity.Models.AdminInfo

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <environment include="Development">
        <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        @*<link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />*@

        <link rel="stylesheet"
              href="http://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/twitter-bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute"
              integrity=""
              crossorigin="anonymous">
    </environment>
</head>
<body>
    <div class="container">
        <h4 class="display-4">ADMIN INFO</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="AdminId" class="control-label"></label>
                        <input asp-for="AdminId" class="form-control" />
                        <span asp-validation-for="AdminId" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Login" class="btn btn-primary" />
                    </div>
                </form>
            </div>
            <div class="col-md-8">
                <img class="img-fluid" src="~/img/login.jpg" />

            </div>
        </div>

    </div>

</body>
</html>