CityBusManagementSystem.Api/CityBusManagementSystem.UI/Controllers/BusDetailsController.cs
using CityBusManagement.Entity.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace CityBusManagementSystem.UI.Controllers
{
    public class BusDetailsController : Controller
    {

        private IConfiguration _configuration;
        public BusDetailsController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public async Task<IActionResult> BusDetails()
        {
            IEnumerable<BusDetails> busDetails = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "BusDetails/GetBusDetails";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        busDetails = JsonConvert.DeserializeObject<IEnumerable<BusDetails>>(result);
                    }
                }
            }
            return View(busDetails);
        }
        public IActionResult BusDetailsEntry()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> BusDetailsEntry(BusDetails busDetails)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(busDetails), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "BusDetails/AddBusDetails";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "BusDetails details saved successfully!";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong entries!";
                    }
                }
            }
            return View();
        }
        public async Task<IActionResult> DeleteBusDetails(int busNo)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {

                string endPoint = _configuration["WebApiBaseUrl"] + "BusDetails/DeleteBusDetails?busNo=" + busNo;
                using (var response = await client.DeleteAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Bus details Deleted successfully!";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong entries!";
                    }
                }
            }
            return View();
        }
    }
}

CityBusManagementSystem.Api/CityBusManagementSystem.UI/Views/BusDetails/BusDetails.cshtml
@model IEnumerable<CityBusManagement.Entity.Models.BusDetails>


<div class="row">
    <div class="col-12">
        <h3>BusDetails</h3>
        <hr />
        <table class="table table-light table-bordered table-hover">
            <thead>
                <tr>
                    <th>busNo</th>
                    <th>busName</th>
                    <th>arrivalTime</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var busDetails in Model)
                {
                    <tr>
                        <td>@busDetails.busNo</td>
                        <td>@busDetails.busName</td>
                        <td>@busDetails.arrivalTime</td>
                        <td><a asp-controller="BusDetails" asp-action="EditBusDetails" asp-route-busNo="@busDetails.busNo">Edit</a></td>
                        <td><a asp-controller="BusDetails" asp-action="DeleteBusDetails" asp-route-busNo="@busDetails.busNo">Delete</a></td>
                    </tr>
}
            </tbody>
        </table>
    </div>
</div>

CityBusManagementSystem.Api/CityBusManagementSystem.UI/Views/BusDetails/BusDetailsEntry.cshtml
@model CityBusManagement.Entity.Models.BusDetails
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{ }
<form method="post" enctype="multipart/form-data">

    <div class="h2">
        BUS DETAILS ENTRY
    </div>
    <div class="form-group">
        <label>Bus Name</label>
        <input type="text" asp-for="busName" class="form-control" placeholder="enter busName " required />
    </div>
    <div class="form-group">
        <label>Arrival Time</label>
        <input type="text" asp-for="arrivalTime" class="form-control" placeholder="enter arrivalTime" required />
    </div>
    <input type="submit" value="Save" class="btn btn-outline-success" />
    <input type="button" value="Reset" class="btn btn-outline-secondary" />
    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div> }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>}
</form>

<div>
    <a asp-controller="BusDetails" asp-action="BusDetails">Back to List</a>
</div>

CityBusManagementSystem.Api/CityBusManagementSystem.UI/Views/BusDetails/DeleteBusDetails.cshtml
@model CityBusManagement.Entity.Models.BusDetails

<form enctype="multipart/form-data">
    <h2>DELETE BUS DETAILS</h2>

    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }

</form>

<div>
    <a asp-controller="BusDetails" asp-action="BusDetails">View  List</a>
</div>